### PR TITLE
GET /campaigns/:id override fix

### LINKED ISSUE #981: Overrides not appearing in GET campaigns/:id
_BUG_
-------------------
#### Current Behavior
- Overrides for templates on a Campaign don't seem to appear in the `GET /campaigns/:id` response, although we do get the override returned in a `POST /chatbot` mData request.

 Example prod Campaign: 7978

#### Why This Matters
Gambit Conversations relies on the `GET /campaigns/:id` response to populate its cache of Campaign message templates to send.

### PR DESCRIPTION
**Pull request by aaronschachter**
#### What's this PR do?
Fixes #981: A bug introduced by the `config.campaignFields` naming changes in #958, where the `response.data.templates` of a `GET /campaigns/:id` request doesn't include any Campaign overrides, only returns rendered templates of the default Contentful Campaign (`campaignID=default`)

#### How should this be reviewed?
Verify the `gambitSignupMenu` template is overridden in http://ds-mdata-responder-staging.herokuapp.com/v1/campaigns/7

#### Relevant tickets
Fixes #981 

#### Checklist
- [x] Tested on staging.

### CODE REVIEW

File: lib/contentful.js [hunk 1]
```diff
@@ -210,23 +210,24 @@ module.exports.renderMessageForPhoenixCampaign = function (phoenixCampaign, msgT
...
     const campaignContent = {};
     const templates = {};
+    // TODO: Instead of making two Contentful requests (first: for campaignId, second: for default)
+    // use getEntries() with an IN operator get both Contentful Campaigns in a single request.
+    // @see https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters/inclusion
     return exports.fetchCampaign(campaignId)
       .then((contentfulCampaign) => {
         campaignContent.overrides = contentfulCampaign.fields;
-        // TODO: Pass the default Campaign, to avoid fetching every time we call this.
-        // GET campaigns could fetch default once, instead of every time we get each Campaign.
```
Comment (aaronschachter) [inline lib/contentful.js]: This was done via #820
