### PR TITLE
Catch CampaignNotFound and CampaignClosed errors

### LINKED ISSUE #680: Signup for closed campaign crashes app
This is why i've been avoiding logging networking errors, because they end up crashing the app -- https://gist.github.com/aaronschachter/bdc01d044abce10baab2ef26934c45c3

This was triggered by posting a Signup to a closed Campaign and sending the catching the `error` with [l`ogger.error`](https://github.com/DoSomething/gambit/blob/9a789aef79dd1685fd425609e429b0677345fce4/api/controllers/CampaignBotController.js#L462).

### PR DESCRIPTION
**Pull request by aaronschachter**
#### What's this PR do?

* Adds Bluebird [filtered catch](http://bluebirdjs.com/docs/api/catch.html#filtered-catch) to throw/catch new classes `CampaignClosedError` and `CampaignNotFoundError`

* Moves loading current User earlier in sequence in order to send the Closed Campaign message back to member if catching `CampaignClosedError`

    * Refactors logic of loading the User into `router-chatbot` calls to `User` static methods, deprecating `CampaignBotController.loadUser` 

#### How should this be reviewed?
Set up a keyword for a closed Campaign on CampaignBot and text in to verify closed campaign message is sent. 

#### Relevant tickets
Fixes #680

#### Checklist
- [x] Documentation added for new features/changed endpoints.
- [x] Tested on staging.

### CODE REVIEW

File: config/router-chatbot.js [hunk 1]
```diff
@@ -126,31 +124,77 @@ router.post('/', (req, res) => {
...
+          // TODO: Custom newrelic event? Stathat? the keyword needs to be turned off in Mobile Commons
+          // or assigned to a different active CampaignBot Campaign.
+          logger.error(`Received keyword:${scope.keyword} for closed campaign:${campaignID}`);
+
+          const msg = controller.renderResponseMessage(scope, 'campaign_closed');
+          // TODO: This won't work because we don't have a loaded scope.user to update Northstar ID.
+          // Need to load current User before we check for a keyword.
+          postMobileCommonsProfile(scope, msg);
+
+          return res.send(gambitResponse(msg));
```
Comment (aaronschachter) [inline config/router-chatbot.js]: At this point, want to exit out of the chain completely (instead of passing the `res.send()`) to the 2nd `then` at L232

File: config/router-chatbot.js [hunk 2]
```diff
@@ -37,8 +45,6 @@ function postMobileCommonsProfile(req, msg) {
     // Target Mobile Commons OIP must render gambit_chatbot_response in Liquid to deliver the msg.
     // @see https://github.com/DoSomething/gambit/wiki/Chatbot#mobile-commons
     gambit_chatbot_response: msg,
-    // Store campaign for current conversation to expose in a Mobile Commons Profile.
-    gambit_current_campaign: req.campaign._id,
```
Comment (aaronschachter) [inline config/router-chatbot.js]: Removing this for now until there's a need for it -- gets tricky if the saved current campaign is closed.

**Comment by aaronschachter** [comment]
Ready for review. [Updated docs for how to avoid Closed Campaign errors.](https://github.com/DoSomething/gambit/wiki/Chatbot#closed-campaigns)

File: config/router-chatbot.js [hunk 3]
```diff
@@ -7,6 +7,14 @@ const express = require('express');
 const router = express.Router(); // eslint-disable-line new-cap
 const mobilecommons = rootRequire('lib/mobilecommons');
 const logger = app.locals.logger;
+const Promise = require('bluebird');
+
+function CampaignClosedError() {}
```
Comment (sergii-tkachenko) [inline config/router-chatbot.js]: In ES6 extend should work: `class CampaignClosedError extends Error`.

Comment (sergii-tkachenko) [inline config/router-chatbot.js]: It also might make sense to move extensions into own file.

File: config/router-chatbot.js [hunk 4]
```diff
@@ -126,85 +139,127 @@ router.post('/', (req, res) => {
...
+  // TODO: Add reject, and throw new custom errors to indicate various error types.
+  const loadUser = new Promise((resolve) => {
+    logger.log('loadUser');
+
+    if (req.body.profile_northstar_id) {
+      const userID = req.body.profile_northstar_id;
+      return app.locals.db.users
+        .findById(userID)
+        .exec()
+        .then(user => {
```
Comment (sergii-tkachenko) [inline config/router-chatbot.js]: Parentheses.

File: config/router-chatbot.js (hunk 3 above)
Comment (aaronschachter) [inline config/router-chatbot.js]: @sergii-tkachenko Where would you suggest placing the extensions file? into `config` at the same directory? New folder?

Related question -- Is `config` the best place for this `router-chatbot.js` lives? I've following loosely following Sails conventions in attempt to make things easy to find.

Comment (deadlybutter) [inline config/router-chatbot.js]: Depending on the class, It could probably have its own file

**Comment by aaronschachter** [comment]
@sergii-tkachenko Updated! Added a `api/exceptions` to store the custom errors, moved `router.js` and `router-chatbot.js` to project root.
